# Base de datos de verbos irregulares para la aplicación de práctica

VERBS_DB = [
    {"spanish": "ser / estar", "infinitive": "be", "past_simple": "was/were", "past_participle": "been"},
    # {"spanish": "golpear / batir", "infinitive": "beat", "past_simple": "beat", "past_participle": "beaten"},
    {"spanish": "llegar a ser / convertirse en", "infinitive": "become", "past_simple": "became", "past_participle": "become"},
    {"spanish": "empezar / comenzar", "infinitive": "begin", "past_simple": "began", "past_participle": "begun"},
    # {"spanish": "doblar / curvar", "infinitive": "bend", "past_simple": "bent", "past_participle": "bent"},
    # {"spanish": "apostar", "infinitive": "bet", "past_simple": "bet", "past_participle": "bet"},
    #{"spanish": "morder", "infinitive": "bite", "past_simple": "bit", "past_participle": "bitten"},
    #{"spanish": "soplar", "infinitive": "blow", "past_simple": "blew", "past_participle": "blown"},
    {"spanish": "romper", "infinitive": "break", "past_simple": "broke", "past_participle": "broken"},
    {"spanish": "traer", "infinitive": "bring", "past_simple": "brought", "past_participle": "brought"},
    {"spanish": "construir", "infinitive": "build", "past_simple": "built", "past_participle": "built"},
    {"spanish": "comprar", "infinitive": "buy", "past_simple": "bought", "past_participle": "bought"},
    {"spanish": "atrapar / coger", "infinitive": "catch", "past_simple": "caught", "past_participle": "caught"},
    #{"spanish": "elegir", "infinitive": "choose", "past_simple": "chose", "past_participle": "chosen"},
    {"spanish": "venir", "infinitive": "come", "past_simple": "came", "past_participle": "come"},
    {"spanish": "costar", "infinitive": "cost", "past_simple": "cost", "past_participle": "cost"},
    #{"spanish": "cortar", "infinitive": "cut", "past_simple": "cut", "past_participle": "cut"},
    #{"spanish": "tratar / repartir", "infinitive": "deal", "past_simple": "dealt", "past_participle": "dealt"},
    {"spanish": "hacer", "infinitive": "do", "past_simple": "did", "past_participle": "done"},
    #{"spanish": "dibujar", "infinitive": "draw", "past_simple": "drew", "past_participle": "drawn"},
    {"spanish": "beber", "infinitive": "drink", "past_simple": "drank", "past_participle": "drunk"},
    {"spanish": "conducir", "infinitive": "drive", "past_simple": "drove", "past_participle": "driven"},
    {"spanish": "comer", "infinitive": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"spanish": "caer", "infinitive": "fall", "past_simple": "fell", "past_participle": "fallen"},
    #{"spanish": "alimentar", "infinitive": "feed", "past_simple": "fed", "past_participle": "fed"},
    {"spanish": "sentir", "infinitive": "feel", "past_simple": "felt", "past_participle": "felt"},
    #{"spanish": "luchar / pelear", "infinitive": "fight", "past_simple": "fought", "past_participle": "fought"},
    {"spanish": "encontrar", "infinitive": "find", "past_simple": "found", "past_participle": "found"},
    {"spanish": "volar", "infinitive": "fly", "past_simple": "flew", "past_participle": "flown"},
    {"spanish": "olvidar", "infinitive": "forget", "past_simple": "forgot", "past_participle": "forgotten"},
    #{"spanish": "perdonar", "infinitive": "forgive", "past_simple": "forgave", "past_participle": "forgiven"},
    #{"spanish": "congelar", "infinitive": "freeze", "past_simple": "froze", "past_participle": "frozen"},
    {"spanish": "conseguir / obtener", "infinitive": "get", "past_simple": "got", "past_participle": "got/gotten"},
    {"spanish": "dar", "infinitive": "give", "past_simple": "gave", "past_participle": "given"},
    {"spanish": "ir", "infinitive": "go", "past_simple": "went", "past_participle": "gone"},
    #{"spanish": "crecer", "infinitive": "grow", "past_simple": "grew", "past_participle": "grown"},
    #{"spanish": "colgar", "infinitive": "hang", "past_simple": "hung", "past_participle": "hung"},
    {"spanish": "tener / haber", "infinitive": "have", "past_simple": "had", "past_participle": "had"},
    {"spanish": "oír", "infinitive": "hear", "past_simple": "heard", "past_participle": "heard"},
    #{"spanish": "esconder / ocultar", "infinitive": "hide", "past_simple": "hid", "past_participle": "hidden"},
    #{"spanish": "golpear / chocar", "infinitive": "hit", "past_simple": "hit", "past_participle": "hit"},
    #{"spanish": "sostener / mantener", "infinitive": "hold", "past_simple": "held", "past_participle": "held"},
    #{"spanish": "herir / doler", "infinitive": "hurt", "past_simple": "hurt", "past_participle": "hurt"},
    #{"spanish": "mantener / guardar", "infinitive": "keep", "past_simple": "kept", "past_participle": "kept"},
    {"spanish": "saber / conocer", "infinitive": "know", "past_simple": "knew", "past_participle": "known"},
    #{"spanish": "guiar / dirigir", "infinitive": "lead", "past_simple": "led", "past_participle": "led"},
    #{"spanish": "aprender", "infinitive": "learn", "past_simple": "learned/learnt", "past_participle": "learned/learnt"},
    {"spanish": "dejar / salir", "infinitive": "leave", "past_simple": "left", "past_participle": "left"},
    #{"spanish": "prestar", "infinitive": "lend", "past_simple": "lent", "past_participle": "lent"},
    #{"spanish": "dejar / permitir", "infinitive": "let", "past_simple": "let", "past_participle": "let"},
    #{"spanish": "tumbarse / yacer", "infinitive": "lie", "past_simple": "lay", "past_participle": "lain"},
    #{"spanish": "encender / iluminar", "infinitive": "light", "past_simple": "lit/lighted", "past_participle": "lit/lighted"},
    {"spanish": "perder", "infinitive": "lose", "past_simple": "lost", "past_participle": "lost"},
    {"spanish": "hacer / fabricar", "infinitive": "make", "past_simple": "made", "past_participle": "made"},
    #{"spanish": "significar / querer decir", "infinitive": "mean", "past_simple": "meant", "past_participle": "meant"},
    {"spanish": "encontrarse con / conocer", "infinitive": "meet", "past_simple": "met", "past_participle": "met"},
    {"spanish": "pagar", "infinitive": "pay", "past_simple": "paid", "past_participle": "paid"},
    {"spanish": "poner", "infinitive": "put", "past_simple": "put", "past_participle": "put"},
    {"spanish": "leer", "infinitive": "read", "past_simple": "read", "past_participle": "read"},
    #{"spanish": "montar / cabalgar", "infinitive": "ride", "past_simple": "rode", "past_participle": "ridden"},
    #{"spanish": "sonar / llamar (por teléfono)", "infinitive": "ring", "past_simple": "rang", "past_participle": "rung"},
    #{"spanish": "subir / elevarse", "infinitive": "rise", "past_simple": "rose", "past_participle": "risen"},
    {"spanish": "correr", "infinitive": "run", "past_simple": "ran", "past_participle": "run"},
    {"spanish": "decir", "infinitive": "say", "past_simple": "said", "past_participle": "said"},
    #{"spanish": "ver", "infinitive": "see", "past_simple": "saw", "past_participle": "seen"},
    #{"spanish": "vender", "infinitive": "sell", "past_simple": "sold", "past_participle": "sold"},
    #{"spanish": "enviar", "infinitive": "send", "past_simple": "sent", "past_participle": "sent"},
    #{"spanish": "poner / establecer", "infinitive": "set", "past_simple": "set", "past_participle": "set"},
    #{"spanish": "agitar / sacudir", "infinitive": "shake", "past_simple": "shook", "past_participle": "shaken"},
    #{"spanish": "brillar", "infinitive": "shine", "past_simple": "shone", "past_participle": "shone"},
    #{"spanish": "disparar", "infinitive": "shoot", "past_simple": "shot", "past_participle": "shot"},
    #{"spanish": "mostrar / enseñar", "infinitive": "show", "past_simple": "showed", "past_participle": "shown"},
    #{"spanish": "cerrar", "infinitive": "shut", "past_simple": "shut", "past_participle": "shut"},
    #{"spanish": "cantar", "infinitive": "sing", "past_simple": "sang", "past_participle": "sung"},
    #{"spanish": "hundirse", "infinitive": "sink", "past_simple": "sank", "past_participle": "sunk"},
    #{"spanish": "sentarse", "infinitive": "sit", "past_simple": "sat", "past_participle": "sat"},
    #{"spanish": "dormir", "infinitive": "sleep", "past_simple": "slept", "past_participle": "slept"},
    #{"spanish": "deslizarse", "infinitive": "slide", "past_simple": "slid", "past_participle": "slid"},
    #{"spanish": "hablar", "infinitive": "speak", "past_simple": "spoke", "past_participle": "spoken"},
    #{"spanish": "gastar / pasar (tiempo)", "infinitive": "spend", "past_simple": "spent", "past_participle": "spent"},
    #{"spanish": "estar de pie", "infinitive": "stand", "past_simple": "stood", "past_participle": "stood"},
    #{"spanish": "robar", "infinitive": "steal", "past_simple": "stole", "past_participle": "stolen"},
    #{"spanish": "pegar / adherirse", "infinitive": "stick", "past_simple": "stuck", "past_participle": "stuck"},
    #{"spanish": "nadar", "infinitive": "swim", "past_simple": "swam", "past_participle": "swum"},
    #{"spanish": "tomar / llevar", "infinitive": "take", "past_simple": "took", "past_participle": "taken"},
    #{"spanish": "enseñar", "infinitive": "teach", "past_simple": "taught", "past_participle": "taught"},
    #{"spanish": "rasgar / romper", "infinitive": "tear", "past_simple": "tore", "past_participle": "torn"},
    #{"spanish": "decir / contar", "infinitive": "tell", "past_simple": "told", "past_participle": "told"},
    #{"spanish": "pensar", "infinitive": "think", "past_simple": "thought", "past_participle": "thought"},
    #{"spanish": "lanzar / tirar", "infinitive": "throw", "past_simple": "threw", "past_participle": "thrown"},
    #{"spanish": "entender / comprender", "infinitive": "understand", "past_simple": "understood", "past_participle": "understood"},
    #{"spanish": "despertarse", "infinitive": "wake", "past_simple": "woke", "past_participle": "woken"},
    #{"spanish": "llevar puesto / vestir", "infinitive": "wear", "past_simple": "wore", "past_participle": "worn"},
    #{"spanish": "ganar", "infinitive": "win", "past_simple": "won", "past_participle": "won"},
    #{"spanish": "escribir", "infinitive": "write", "past_simple": "wrote", "past_participle": "written"}
]
